[project]
name = "video2llm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-genai>=1.28.0",
    "opencv-python-headless==4.10.0.84",
    "pillow==10.4.0",
    "python-dotenv>=1.1.1",
    "typer==0.12.3",
]
